# Your Name or Company
title: Uni Kravitz

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: This is a temporary test website to show that is it possible to deploy websites easily.

# Half layout options
half_side: left
half_image: woman-half.jpg

# Add your social links
#social:
#  - platform: github
#    url: https://github.com/itm311
#  - platform: facebook
#    url: https://facebook.com/brianmaierjr
#  - platform: twitter
#    url: https://twitter.com/brianmaierjr
#  - platform: linkedin
 #   url: brianmaierjr

# General settings
url: http://itm311.com
baseurl: ""
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking
permalink: pretty

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
